In [1]:
import numpy as np 

In [5]:
matrix=[[1,2,3],[0,1,4],[5,6,0]]
matrix=np.array(matrix)
inverse=np.linalg.inv(matrix)
result=np.round(matrix @ inverse)
print(result)

[[ 1. -0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
